server:
  port: 8765
  
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
      routes:
        - id: experience-service
          uri: lb://EXPERIENCE-SERVICE
          predicates:
            - Path=/experience/**
          filters:
            - AuthenticationFilter

        - id: industry-service
          uri: lb://INDUSTRY-SERVICE
          predicates:
            - Path=/industry/**
          filters:
            - AuthenticationFilter

        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/auth/**

  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
