server:
  port: 0
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

spring:
  liquibase:
    enabled: false
  application:
    name: INDUSTRY-SERVICE
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}




